# Generated by Django 5.2.7 on 2025-10-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
